repositories:
  - name: flannel
    url: https://flannel-io.github.io/flannel/
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server/

releases:
  - name: flannel
    namespace: kube-flannel
    chart: flannel/flannel
    version: 0.22.1
    values:
      - flannel/values.yaml
  - name: metrics-server
    namespace: kube-system
    chart: metrics-server/metrics-server
    version: 3.10.0
    values:
      - metrics-server/values.yaml
